version: '3'

services:
  app:
    build: .
    ports:
      - "5173:5173"  # Changed from 3000:3000 to match Vite's default port
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
